substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: d1mini_dht22
  friendly_name: D1Mini DHT22
  ip_address: !secret d1mini_dht22_ip


esphomeyaml:
  # https://esphome.io/components/esphomeyaml
  name: ${device_name}
  platform: ESP8266
  board: nodemcuv2


wifi:
  # https://esphome.io/components/wifi
  hostname: ${device_name}
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1
    dns2: !secret wifi_dns2


logger:
  # https://esphome.io/components/logger


api:
  # https://esphome.io/components/api
  # password: !secret esphome_api_password


ota:
  # https://esphome.io/components/ota
  password: !secret esphome_ota_password


# web_server:
#   # https://esphomelib.com/esphomeyaml/components/web_server.html
#   port: 80


sensor:
  # https://esphomelib.com/esphomeyaml/components/sensor
  - platform: dht
    # https://esphomelib.com/esphomeyaml/components/sensor/dht.html
    pin: D1
    temperature:
      name: ${friendly_name} Temperature
      filters:
        - filter_nan:
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
        - lambda: return x * (9.0/5.0) + 32.0; # report temperature in Fahrenheit
      unit_of_measurement: "°F"
      # icon: "mdi:thermometer"   # temperature gets thermometer icon by default
      # accuracy_decimals: 1      # temperature gets 1 decimal by default
    humidity:
      name: ${friendly_name} Humidity
      filters:
        - filter_nan:
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
      # icon: "mdi:water-percent" # humidity gets water-percent icon by default
      accuracy_decimals: 1        # humidity gets 0 decimals by default
    model: AM2302                 # dht22 (attached board w/3 pins)
    update_interval: 10s
