##############################
# Info:
#   Combines an esp8266 (D1-Mini), SCT-013 current sensor, and a relay.
#   Use SCT-013 to sense power usage from a device and relay to control power to a secondary device.
#   In this case, sense TV power usage and control power to a Chromecast.  
##############################
# Requires:
#   sct013_1000.h   ->   Place sct013_1000.h in the same directory with this yaml file. "PollingComponent" = analog sensor polling interval 
##############################


substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: basement_chromecast_controller
  friendly_name: Basement Chromecast Controller
  ip_address: !secret basement_chromecast_controller_ip
  trigger_threshold: '20.0'   # Varies per device. Set this number 10 or 20 above device standby sensor value; see "Analog Input Sensor Value" in the logs
  update_interval: 5s   # interval to test polled values (recommend 5s or greater). Only required if incorporating a relay.


esphome:
  # https://esphome.io/components/esphome
  name: $device_name
  platform: ESP8266
  board: d1_mini
  includes:
    - sct013_1000.h
  libraries:
    - "EmonLib"


wifi:
  # https://esphome.io/components/wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: $ip_address
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1


# web_server:
#   port: 80
  # https://esphome.io/components/web_server.html


logger:
  # https://esphome.io/components/logger


api:
  # password: !secret esphome_api_password
  # https://esphome.io/components/api


ota:
  password: !secret esphome_ota_password
  # https://esphome.io/components/ota


sensor:
  - platform: custom
    # https://esphome.io/components/sensor/custom
    lambda: |-
      auto my_sensor = new MyCustomSensor();
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      name: $friendly_name Sensor Value
      id: sensor
      unit_of_measurement: W
      filters:
        - delta: 2
    internal: True


binary_sensor:
  - platform: template
    # https://esphome.io/components/binary_sensor/template
    name: $friendly_name Sensor Status
    id: sensor_status
    lambda: |-
      if (id(sensor).state >= $trigger_threshold) {
        return true;
      } else {
        return false;
      }

# this section only required if incorporating a relay----------#
  - platform: template
    # https://esphome.io/components/binary_sensor/template
    name: $friendly_name Relay Status
    id: relay_status
    lambda: |-
      if (id(device_state).state == "Active") {
        return true;
      } else {
        return false;
      }
    on_press:
      then:
        - switch.turn_on: relay
    on_release:
      then:
        - switch.turn_off: relay
    internal: True


text_sensor:
  - platform: template
    # https://esphome.io/components/text_sensor/template.html
    id: device_state
    lambda: |-
      if (id(sensor).state >= $trigger_threshold) {
        return {"Active"};
      } else {
        return {"Standby"};
      }
    update_interval: $update_interval   # give the sensor enough time to stabilize from spike after the relay turns on/off


switch:
  - platform: gpio
    # https://esphome.io/components/switch/gpio
    pin: D1
    id: relay
# ---------- this section only required if incorporating a relay #
